---
abstract: 'Object-Oriented inteface for Nagios:: MKLivestatus'
author:
  - 'Robert Bohne <rbo@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Nagios-MKLivestatus-Class
no_index:
  directory:
    - inc
    - t
requires:
  Module::Find: 0
  Moose: 0
  Nagios::MKLivestatus: 0.28
resources:
  license: http://dev.perl.org/licenses/
version: 0.01
